### ISSUE TITLE
Compilation errors in Sound.cpp

### ISSUE THREAD

**Issue by Mailaender** [griefly/griefly#260]
I tried to compile and package griefly, but it won't compile:

```
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp: In member function 'void SoundManager::InitSound(sf::Sound*, const string&)':
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:17:12: error: 'class sf::Sound' has no member named 'setBuffer'
[  119s]      sound->setBuffer(*GetBuffer(name));
[  119s]             ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp: In member function 'void SoundManager::LoadSound(const string&)':
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:24:25: error: 'class sf::SoundBuffer' has no member named 'loadFromFile'
[  119s]      if (!holder_[name]->loadFromFile("sounds/" + name))
[  119s]                          ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp: In function 'void PlaySound(sf::Sound*, const string&)':
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:45:17: error: 'class sf::Sound' has no member named 'getBuffer'
[  119s]      if (!sound->getBuffer())
[  119s]                  ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:49:16: error: 'class sf::Sound' has no member named 'getStatus'
[  119s]      if (sound->getStatus() != sf::SoundSource::Playing)
[  119s]                 ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:49:35: error: 'sf::SoundSource' has not been declared
[  119s]      if (sound->getStatus() != sf::SoundSource::Playing)
[  119s]                                    ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:51:16: error: 'class sf::Sound' has no member named 'play'
[  119s]          sound->play();
[  119s]                 ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp: In member function 'sf::Sound* SoundPlayer::PlaySound(const string&)':
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:71:24: error: '__gnu_cxx::__alloc_traits<std::allocator<sf::Sound> >::value_type {aka class sf::Sound}' has no member named 'getStatus'
[  119s]          if (sounds_[i].getStatus() == sf::SoundSource::Stopped)
[  119s]                         ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:71:43: error: 'sf::SoundSource' has not been declared
[  119s]          if (sounds_[i].getStatus() == sf::SoundSource::Stopped)
[  119s]                                            ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:83:16: error: '__gnu_cxx::__alloc_traits<std::allocator<sf::Sound> >::value_type {aka class sf::Sound}' has no member named 'setVolume'
[  119s]      sounds_[i].setVolume(15.0f);
[  119s]                 ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:84:16: error: '__gnu_cxx::__alloc_traits<std::allocator<sf::Sound> >::value_type {aka class sf::Sound}' has no member named 'play'
[  119s]      sounds_[i].play();
[  119s]                 ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp: In member function 'void SoundPlayer::PlayMusic(const string&, float)':
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:92:17: error: 'class sf::Music' has no member named 'openFromFile'
[  119s]      if (!music_.openFromFile("music/" + name))
[  119s]                  ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:97:12: error: 'class sf::Music' has no member named 'setLoop'
[  119s]      music_.setLoop(true);
[  119s]             ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:98:12: error: 'class sf::Music' has no member named 'setVolume'
[  119s]      music_.setVolume(volume);
[  119s]             ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:99:12: error: 'class sf::Music' has no member named 'play'
[  119s]      music_.play();
[  119s]             ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp: In member function 'void SoundPlayer::StopMusic()':
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:104:16: error: 'class sf::Music' has no member named 'getStatus'
[  119s]      if (music_.getStatus() != sf::Music::Status::Stopped)
[  119s]                 ^
[  119s] /home/abuild/rpmbuild/BUILD/griefly-0.3.1/Sources/representation/Sound.cpp:106:16: error: 'class sf::Music' has no member named 'stop'
[  119s]          music_.stop();
[  119s]                 ^
```

https://build.opensuse.org/package/show/home:Mailaender:branches:games/griefly

**Comment by kremius** [comment]
It is really looks like SFML version trouble, because SFML 1.* have different API from SFML 2.\*. All methods names in 1.\* are camel-cased (e.g, `LoadFromFile` versus `loadFromFile` in SFML 2.\*). So it is **really** needed to choose right version of SFML.

**Comment by Chemrat** [comment]
Indeed, you're trying to build with SFML 1.6

See https://build.opensuse.org/public/build/home:Mailaender:branches:games/openSUSE_Tumbleweed/x86_64/griefly/_log

Package ``libsfml1_6`` is in use

**Comment by Mailaender** [comment]
Yes. That fixed it. I didn't read the README thoroughly and thought `cmake` would complain.

**Comment by kremius** [comment]
Yep, that's kind of bad that CMake does not check libs #184
