### PR TITLE
FIX: Competing namespaces for abs

### PR DESCRIPTION
**Pull request by gaddox**
Compiling with Clang 5.0.1 on OpenBSD fails on `Representation.cpp`:

```
/home/gaddox/Documents/griefly/sources/client/representation/Representation.cpp:401:16: error: call to 'abs' is ambiguous
    distance = std::abs(distance);
```

This is likely due to operator overloading on `abs`, in `cmath` and `stdlib.h`. Removing the namespace here forces the `stdlib.h` interpretation of `abs`. `distance` is an int so using the C-style `abs` is fine. 

Otherwise, after changing the default Qt5 cmake path, Griefly compiles on OpenBSD 6.3 with Clang 5.0.1.

### CODE REVIEW

**Comment by kremius** [comment]
I am not sure that it is the right way to solve this issue. Can you provide more complete compile error message (usually a compiler should provide a list of possible function candidates)?
I feel like something is off here.

**Comment by gaddox** [comment]
The clusterfuck of mathlibs is supposed to be taken care of in G++ for C++14, but perhaps not for Clang.

Make output, with candidate functions:

```
/home/gaddox/Documents/griefly/sources/client/representation/Representation.cpp:401:16: error: call to 'abs' is ambiguous
    distance = std::abs(distance);
               ^~~~~~~~
/usr/include/c++/v1/math.h:646:1: note: candidate function
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^
/usr/include/c++/v1/math.h:650:1: note: candidate function
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
^
/usr/include/c++/v1/math.h:654:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
3 warnings and 1 error generated.
*** Error 1 in . (sources/client/CMakeFiles/KVClient.dir/build.make:311 'sources/client/CMakeFiles/KVClient.dir/representation/Representation.cpp.o')
*** Error 1 in . (CMakeFiles/Makefile2:236 'sources/client/CMakeFiles/KVClient.dir/all')
*** Error 1 in /home/gaddox/Documents/griefly/build (Makefile:130 'all')
```

**Comment by kremius** [comment]
Can you try to include `<cstdlib>` header instead in this file? Just some guess, I don't have installed clang right now to check it properly.

**Comment by gaddox** [comment]
Compiles.

**Comment by kremius** [comment]
Will you create another pull request? Just if a header should be added to proper compilation it is still should be fixed in the master branch.
